### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by Fluto** [Sanae6/TaikoDiscordRPC#1]
Any particular reason why this logic is in `FixedUpdate()` and not `Update()`? 

https://github.com/Sanae6/TaikoDiscordRPC/blob/aa06f349c8739625a1297403f60dfa8688af1273/TaikoDiscordRPC/Program.cs#L158

**Comment by Sanae6** [comment]
I picked `FixedUpdate` because I thought that it ran on a selected `n` frames per second, but after looking it up, I should have just used `Update` as I had the two reversed. I'll change it in an update.
