### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by Mothnmoth** [Sanae6/TaikoDiscordRPC#2]
This mod seems interesting as the default rich presence for TDM is trash. But for some reason this doesn't seem to be working for me at least not anymore... is this meant for an old version of TDM or does it work for the newer ones too? I'm currently on the latest version of the game however i once tried this mod on an old version of TDM and it worked.

**Comment by Sanae6** [comment]
Unfortunately, no. I used to have access to the game through XBox Gamepass when it released, but not anymore. Any versions after ~1mo post-release are unsupported, as I don't have any way to run the game or test mods.
